baseURL = "https://zhangt.ai"
title = "Zhang Tai - 张泰"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = "© 2021 Zhang Tai | powered by Hugo, theme by minimo, hosted on Cloudflare Pages"

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 10
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "DevOps Engineer, Jenkins Specialist"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.png"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = ""
startYear = ""
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false

[params.sidebar]
enable = false

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about","search","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "tai.zhang@outlook.com"
facebook = "zhangtai"
github = "zhangtai"
instagram = "zhangtai"
linkedin = "zhangtai"
twitter = "zhangtai_me"
wechat = "wechat-zhangtai-qr.jpg"


[params.social.config]
platforms = ["github","facebook","twitter","email","linkedin", "wechat"]

[params.comments]
enable = false

[params.search]
client = "fuse" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1

[[menu.main]]
name = "Home"
weight = -10
identifier = "/"
url = "/"

[[menu.main]]
name = "Blog"
weight = -9
identifier = "/blog"
url = "/blog"

[markup.goldmark.renderer]
unsafe= true